# 知识库博客部署工作流
name: Deploy Hugo site to Pages

on:
  # 当推送到 master 分支时触发（请根据你的默认分支修改）
  push:
    branches:
      - master  # 如果你的主分支是 main，请改为 main

  # 允许手动在 Actions 页面触发
  workflow_dispatch:

# 设置 GITHUB_TOKEN 权限，允许部署 Pages
permissions:
  contents: read
  pages: write
  id-token: write

# 并发控制：同一时间只运行一个部署任务，不取消进行中的任务
concurrency:
  group: "pages"
  cancel-in-progress: false

# 默认使用 bash
defaults:
  run:
    shell: bash

jobs:
  # 构建 job
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.148.1  # 请确保这是你实际使用的 Hugo 版本
    steps:
      - name: Checkout 代码
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
            && sudo dpkg -i ${{ runner.temp }}/hugo.deb

      # 若你使用 Sass/SCSS，取消注释以下步骤
      - name: Install Dart Sass
        run: sudo snap install dart-sass

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4

      - name: Install Node.js dependencies (if exists)
        run: "[[ -f package-lock.json || -f npm-shrinkwrap.json ]] && npm ci || true"

      - name: Build with Hugo
        env:
          HUGO_ENVIRONMENT: production
          HUGO_ENV: production
        run: |
          hugo \
            --gc \
            --minify \
            --baseURL "${{ steps.pages.outputs.base_url }}/"

      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./public

  # 部署 job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
